/* 识字 Zeichentrainer — the app's own texts in other languages (v253, H: "Multi language UI and translations").
   English is the key: t("Save card") looks the sentence up in the current language and falls back to the English text
   itself, so a missing translation shows English, never a key. {0}, {1} … are filled in by t(); a count word ("card",
   "cards") may carry the number as {0} where the language puts it elsewhere ("カード{0}枚"). The learning content stays
   Chinese, pinyin and the meaning; the owner's tools (Diagnostics, All users, Feedback, the usage report) stay English.
   To add a language: one more entry in LANGS and one more column below. */
const LANGS=[["en","English"],["de","Deutsch"],["fr","Français"],["es","Español"],["ja","日本語"],["ko","한국어"]];
const LANG_LOCALE={en:"en-GB",de:"de-DE",fr:"fr-FR",es:"es-ES",ja:"ja-JP",ko:"ko-KR"};
let LANG="en";
function langDefault(){ const l=String(navigator.language||"").toLowerCase().slice(0,2); return LANGS.some(([c])=>c===l)?l:"en"; }
function t(key,...args){ const d=L10N[LANG]; let s=d&&d[key]!=null?d[key]:null; if(s==null) s=L10N.en&&L10N.en[key]!=null?L10N.en[key]:key; /* a key with a prefix ("capsule:Done") has its English in the en column */ return args.length?s.replace(/\{(\d)\}/g,(m,i)=>args[+i]!=null?args[+i]:m):s; }
/* a count with its word: nOf(3,"card") → "3 cards" / "3 Karten" / "カード3枚"; pl = an irregular plural key */
function nOf(n,w,pl){ n=n||0; const key=n===1?w:(pl||w+"s"), d=L10N[LANG], tr=d&&d[key]!=null?d[key]:key; return tr.includes("{0}")?tr.replace("{0}",n):`${n} ${tr}`; }
const L10N={
en:{"capsule:Done":"Done"}, /* only the keys whose English differs from the key itself: one English word, two translations */
de:{
  "Photos stay on this phone. Frame the text — the card is made for you.":"Fotos bleiben auf diesem Telefon. Rahme den Text ein – die Karte wird für dich gemacht.",
  "Take photo":"Foto aufnehmen",
  "From album":"Aus dem Album",
  "Processing photo …":"Foto wird verarbeitet …",
  "No photos yet.":"Noch keine Fotos.",
  "Inbox ({0})":"Eingang ({0})",
  "Crop":"Ausschnitt",
  "Turn the frame":"Rahmen drehen",
  "Draw a frame with your finger over the text — corners resize it, dragging inside moves it, the round handle turns it.":"Zieh mit dem Finger einen Rahmen über den Text – die Ecken ändern die Größe, Ziehen innen verschiebt ihn, der runde Griff dreht ihn.",
  "Finding the text …":"Text wird gesucht …",
  "Finding the frame …":"Rahmen wird gesucht …",
  "Reading in a moment — drag a corner first if the frame is off.":"Wird gleich gelesen – zieh vorher an einer Ecke, falls der Rahmen nicht passt.",
  "The frame the card was cut with — adjust it to read again.":"Der Rahmen, mit dem die Karte ausgeschnitten wurde – verschiebe ihn, um neu zu lesen.",
  " Tap outside the frame for the whole photo.":" Tippe außerhalb des Rahmens für das ganze Foto.",
  " Tap outside the frame to enlarge it again.":" Tippe außerhalb des Rahmens, um wieder zu vergrößern.",
  "Read now":"Jetzt lesen",
  "Image only":"Nur das Bild",
  "Frame too small — draw again.":"Rahmen zu klein – zeichne ihn neu.",
  "Reading failed: {0}":"Lesen fehlgeschlagen: {0}",
  " still at: {0}":" hängt bei: {0}",
  " Still at: {0}":" Hängt bei: {0}",
  "Save now":"Jetzt speichern",
  "Card saved — the text follows when the reading is done.":"Karte gespeichert – der Text folgt, sobald das Lesen fertig ist.",
  "No Chinese characters recognized — frame the characters tightly and try again.":"Keine chinesischen Zeichen erkannt – rahme die Zeichen eng ein und versuch es noch einmal.",
  "Card saved — {0}.":"Karte gespeichert – {0}.",
  " Translation pending.":" Übersetzung ausstehend.",
  " Flagged for review.":" Zur Prüfung markiert.",
  "Read as “{0}”. ":"Gelesen als „{0}“. ",
  "Picture taken, the text stays. ":"Bild übernommen, der Text bleibt. ",
  "Adjust the frame to read again, or save.":"Verschiebe den Rahmen, um neu zu lesen, oder speichere.",
  "Characters":"Zeichen",
  " (traditional, as on the photo)":" (Langzeichen, wie auf dem Foto)",
  "Pinyin":"Pinyin",
  "Meaning":"Bedeutung",
  "⚑ Flag for review (text, pinyin or meaning looks wrong)":"⚑ Zur Prüfung markieren (Text, Pinyin oder Bedeutung wirkt falsch)",
  "Note for the reviewer (optional)":"Notiz für den Prüfer (optional)",
  "Tags":"Tags",
  "Chinese class, HSK 3 …":"Chinesischkurs, HSK 3 …",
  "Save card":"Karte speichern",
  "Ask AI":"KI fragen",
  "This reading looks wrong — frame the text tightly and read again, or fix the characters.":"Diese Lesung scheint falsch – rahme den Text eng ein und lies neu, oder korrigiere die Zeichen.",
  " The reading looks uncertain (confidence {0}%) — check the text.":" Die Lesung wirkt unsicher ({0} % sicher) – prüfe den Text.",
  "Only {0} found — if the photo shows more, frame the characters tightly and drag a corner to read again.":"Nur {0} gefunden – zeigt das Foto mehr, rahme die Zeichen eng ein und zieh an einer Ecke, um neu zu lesen.",
  "character":"{0} Zeichen",
  "characters":"{0} Zeichen",
  "Read from the picture by the AI":"Von der KI aus dem Bild gelesen",
  "Meaning {0}, unverified":"Bedeutung {0}, ungeprüft",
  "from the phrasebook":"aus dem Sprachführer",
  "composed word by word":"Wort für Wort zusammengesetzt",
  "from the offline translation":"aus der Offline-Übersetzung",
  "The AI suggested {0}, but {1} was read clearly, so the reading stays. ":"Die KI schlug {0} vor, aber {1} wurde klar gelesen, also bleibt die Lesung. ",
  "This text looks misread{0} — unverified":"Dieser Text scheint falsch gelesen{0} – ungeprüft",
  "Offline translation failed, meaning composed word by word":"Offline-Übersetzung fehlgeschlagen, Bedeutung Wort für Wort zusammengesetzt",
  "Translating …":"Wird übersetzt …",
  "This text is already saved from this photo.":"Dieser Text ist von diesem Foto schon gespeichert.",
  "The AI could not be reached":"Die KI war nicht erreichbar",
  ". Tap Ask AI to try again.":". Tippe auf „KI fragen“, um es noch einmal zu versuchen.",
  "The AI check failed: {0}":"Die KI-Prüfung ist fehlgeschlagen: {0}",
  "Checking pinyin and meaning …":"Pinyin und Bedeutung werden geprüft …",
  "Type the text below.":"Tippe den Text unten ein.",
  "Tap a character to change it":"Tippe auf ein Zeichen, um es zu ändern",
  ", or type the line below":", oder tippe die Zeile unten ein",
  "Tap the characters to remove, then Remove.":"Tippe auf die Zeichen, die weg sollen, dann auf Entfernen.",
  "Select":"Auswählen",
  "Remove":"Entfernen",
  "Remove {0}":"{0} entfernen",
  "Done":"Fertig",
  "Add a character {0}:":"Zeichen {0} einfügen:",
  "at the start":"am Anfang",
  "at the end":"am Ende",
  "between {0} and {1}":"zwischen {0} und {1}",
  "Replace {0} with:":"{0} ersetzen durch:",
  "Close":"Schließen",
  "No match — draw it or ask the AI.":"Kein Treffer – zeichne es oder frag die KI.",
  "Asking the AI …":"KI wird gefragt …",
  "Not here? Draw it":"Nicht dabei? Zeichnen",
  "Add a character:":"Zeichen einfügen:",
  "+ before {0}":"+ vor {0}",
  "+ after {0}":"+ nach {0}",
  "The AI has no better idea.":"Die KI hat keine bessere Idee.",
  "Draw the character below.":"Zeichne das Zeichen unten.",
  "The character in the photo (drag to move, pinch to zoom) — draw it below.":"Das Zeichen im Foto (ziehen zum Verschieben, zwei Finger zum Zoomen) – zeichne es unten.",
  "the character in the photo":"das Zeichen im Foto",
  "Draw all strokes, then tap Done.":"Zeichne alle Striche, dann tippe auf Fertig.",
  "Undo":"Rückgängig",
  "Clear":"Löschen",
  "Draw the character first.":"Zeichne zuerst das Zeichen.",
  "reading …":"wird gelesen …",
  "reading … {0}%":"wird gelesen … {0} %",
  "Read as — tap the right one. Not there? Clear and draw again.":"Gelesen als – tippe auf das richtige. Nicht dabei? Löschen und neu zeichnen.",
  "Not recognized — try cleaner, well-separated strokes.":"Nicht erkannt – versuch es mit sauberen, getrennten Strichen.",
  "saved before the reading was done, and the reading is weak — check text, pinyin and meaning":"vor dem Ende des Lesens gespeichert, und die Lesung ist schwach – Text, Pinyin und Bedeutung prüfen",
  "saved before the reading was done — check text, pinyin and meaning":"vor dem Ende des Lesens gespeichert – Text, Pinyin und Bedeutung prüfen",
  "the new frame could not be read — the old text stays":"der neue Rahmen konnte nicht gelesen werden – der alte Text bleibt",
  "the reading failed — edit the card or frame the photo again":"das Lesen ist fehlgeschlagen – bearbeite die Karte oder rahme das Foto neu ein",
  "the reading looks wrong":"die Lesung scheint falsch",
  "time":"{0}-mal","times":"{0}-mal","AI check":"{0} KI-Prüfung","AI checks":"{0} KI-Prüfungen",
  "Due":"Fällig","capsule:Done":"Fertig","Deck":"Karten","Learn":"Lernen","Cards":"Karten","Camera":"Kamera","More":"Mehr",
  "Language":"Sprache","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"Die Texte der App. Die Karten behalten Chinesisch, Pinyin und Bedeutung.",
  "Loading …":"Lädt …","No cards yet.":"Noch keine Karten.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"Fotografiere ein Schild, eine Speisekarte oder eine Verpackung unter <b>Kamera</b> – oder trage ein Wort von Hand ein unter <b>Karten → + Neu</b>.",
  "Take a photo":"Foto aufnehmen","All clear.":"Alles erledigt.","Pulled-forward round finished.":"Vorgezogene Runde beendet.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"Heute ist nichts fällig. Komm morgen wieder – oder zieh die nächsten Karten vor.",
  "Pull the next cards forward":"Nächste Karten vorziehen","Again":"Nochmal","Hard":"Schwer","Good":"Gut","Easy":"Leicht",
  "⚑ Clear flag":"⚑ Markierung entfernen","⚑ Flag for review":"⚑ Zur Prüfung markieren","✎ Edit":"✎ Bearbeiten",
  "Tap the character to reveal":"Tippe auf das Zeichen für die Antwort",", or the photo for the whole picture":", oder auf das Foto für das ganze Bild",
  "← Cards":"← Karten","Testing from the list":"Test aus der Liste","<10 min":"<10 Min","<1 d":"<1 T","1 d":"1 T","{0} d":"{0} T",
  "{0} learned, {1} reviewed this week, streak {2}":"{0} gelernt, {1} diese Woche wiederholt, Serie {2}",
  "card":"{0} Karte","cards":"{0} Karten","day":"{0} Tag","days":"{0} Tage","review":"{0} Wiederholung","reviews":"{0} Wiederholungen","photo":"{0} Foto","photos":"{0} Fotos",
  "AI suggestion waiting":"{0} KI-Vorschlag wartet","AI suggestions waiting":"{0} KI-Vorschläge warten",
  "Traditional":"Langzeichen","Simplified":"Kurzzeichen","Nothing could be read.":"Es konnte nichts gelesen werden.","Reading the text …":"Text wird gelesen …",
  "meaning unverified":"Bedeutung ungeprüft"," (translation pending)":" (Übersetzung ausstehend)"," (reading uncertain: {0})":" (Lesung unsicher: {0})",
  "Also on another photo":"Auch auf einem anderen Foto","Also on {0} other photos":"Auch auf {0} anderen Fotos","Show this photo":"Dieses Foto zeigen","Open this card":"Diese Karte öffnen",
  "Loading the dictionary …":"Wörterbuch wird geladen …","not in the dictionary":"nicht im Wörterbuch","Dictionary not available.":"Wörterbuch nicht verfügbar.","Pronounce":"Aussprechen",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"Keine chinesische Stimme auf diesem Telefon – füge eine hinzu unter Einstellungen, Text-in-Sprache.",
  "⚑ Review":"⚑ Prüfen","New":"Neu","Review":"Wiederholen","⚑ Flagged for review":"⚑ Zur Prüfung markiert",
  "failed {0} times in a row — check text, meaning and photo":"{0}-mal hintereinander nicht gewusst – Text, Bedeutung und Foto prüfen",
  "AI: this text looks misread":"KI: dieser Text scheint falsch gelesen","Dismiss":"Verwerfen","AI suggestion":"KI-Vorschlag",": looks right":": sieht richtig aus","Accept":"Übernehmen","Mark verified":"Als geprüft markieren","Accept all":"Alle übernehmen",
  "All cards":"Alle Karten","Untagged":"Ohne Tag","Untagged ({0})":"Ohne Tag ({0})",
  "Nothing read":"Nichts gelesen","Reading …":"Wird gelesen …","AI":"KI","No cards match.":"Keine Karte passt.",
  "No cards yet — take a photo under Camera, or tap + New.":"Noch keine Karten – nimm ein Foto auf unter Kamera, oder tippe auf + Neu.",
  "Search":"Suchen","+ New":"+ Neu","⚑ Flagged ({0})":"⚑ Markiert ({0})","AI ({0})":"KI ({0})","Unverified ({0})":"Ungeprüft ({0})","{0} of {1}":"{0} von {1}",
  "due":"fällig","in {0} d":"in {0} T",
  "Interval {0} d, ease {1}, {2}, next {3}.":"Intervall {0} T, Leichtigkeit {1}, {2}, nächste {3}.","Not studied yet.":"Noch nicht gelernt.",
  "Nothing read yet":"Noch nichts gelesen","unverified":"ungeprüft","translation pending":"Übersetzung ausstehend","reading uncertain":"Lesung unsicher",
  "The new frame is being read — the text follows when it is done.":"Der neue Ausschnitt wird gelesen – der Text folgt, sobald es fertig ist.",
  "The text, pinyin and meaning follow when the reading is done.":"Text, Pinyin und Bedeutung folgen, sobald das Lesen fertig ist.",
  "Tap the character to show the answer":"Tippe auf das Zeichen für die Antwort","Tap the character to hide the answer":"Tippe auf das Zeichen, um die Antwort zu verbergen",
  "Test this card":"Diese Karte testen","Edit":"Bearbeiten","Delete card":"Karte löschen","Delete “{0}”?":"„{0}“ löschen?","Delete this card?":"Diese Karte löschen?",
  "The card and its learning progress will be removed.":"Die Karte und ihr Lernfortschritt werden entfernt.","Delete":"Löschen","Cancel":"Abbrechen",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"Du bist in WeChat. Öffne diese Seite im Browser, um die App zu installieren und deine Karten zu behalten."
},
fr:{
  "Photos stay on this phone. Frame the text — the card is made for you.":"Les photos restent sur ce téléphone. Cadrez le texte – la carte est créée pour vous.",
  "Take photo":"Prendre une photo",
  "From album":"Depuis l'album",
  "Processing photo …":"Traitement de la photo …",
  "No photos yet.":"Pas encore de photos.",
  "Inbox ({0})":"Reçues ({0})",
  "Crop":"Cadrer",
  "Turn the frame":"Tourner le cadre",
  "Draw a frame with your finger over the text — corners resize it, dragging inside moves it, the round handle turns it.":"Tracez un cadre avec le doigt sur le texte – les coins le redimensionnent, glisser à l'intérieur le déplace, la poignée ronde le tourne.",
  "Finding the text …":"Recherche du texte …",
  "Finding the frame …":"Recherche du cadre …",
  "Reading in a moment — drag a corner first if the frame is off.":"Lecture dans un instant – déplacez d'abord un coin si le cadre est décalé.",
  "The frame the card was cut with — adjust it to read again.":"Le cadre avec lequel la carte a été découpée – ajustez-le pour relire.",
  " Tap outside the frame for the whole photo.":" Touchez hors du cadre pour la photo entière.",
  " Tap outside the frame to enlarge it again.":" Touchez hors du cadre pour agrandir à nouveau.",
  "Read now":"Lire maintenant",
  "Image only":"Image seule",
  "Frame too small — draw again.":"Cadre trop petit – tracez-le à nouveau.",
  "Reading failed: {0}":"Échec de la lecture : {0}",
  " still at: {0}":" toujours à : {0}",
  " Still at: {0}":" Toujours à : {0}",
  "Save now":"Enregistrer maintenant",
  "Card saved — the text follows when the reading is done.":"Carte enregistrée – le texte suivra une fois la lecture terminée.",
  "No Chinese characters recognized — frame the characters tightly and try again.":"Aucun caractère chinois reconnu – cadrez les caractères au plus près et réessayez.",
  "Card saved — {0}.":"Carte enregistrée – {0}.",
  " Translation pending.":" Traduction en attente.",
  " Flagged for review.":" Signalée à vérifier.",
  "Read as “{0}”. ":"Lu comme « {0} ». ",
  "Picture taken, the text stays. ":"Image prise, le texte reste. ",
  "Adjust the frame to read again, or save.":"Ajustez le cadre pour relire, ou enregistrez.",
  "Characters":"Caractères",
  " (traditional, as on the photo)":" (traditionnels, comme sur la photo)",
  "Pinyin":"Pinyin",
  "Meaning":"Sens",
  "⚑ Flag for review (text, pinyin or meaning looks wrong)":"⚑ Signaler à vérifier (texte, pinyin ou sens douteux)",
  "Note for the reviewer (optional)":"Note pour le relecteur (facultatif)",
  "Tags":"Étiquettes",
  "Chinese class, HSK 3 …":"Cours de chinois, HSK 3 …",
  "Save card":"Enregistrer la carte",
  "Ask AI":"Demander à l'IA",
  "This reading looks wrong — frame the text tightly and read again, or fix the characters.":"Cette lecture semble fausse – cadrez le texte au plus près et relisez, ou corrigez les caractères.",
  " The reading looks uncertain (confidence {0}%) — check the text.":" La lecture semble incertaine (confiance {0} %) – vérifiez le texte.",
  "Only {0} found — if the photo shows more, frame the characters tightly and drag a corner to read again.":"Seulement {0} – si la photo en montre plus, cadrez les caractères au plus près et déplacez un coin pour relire.",
  "character":"{0} caractère trouvé",
  "characters":"{0} caractères trouvés",
  "Read from the picture by the AI":"Lu sur l'image par l'IA",
  "Meaning {0}, unverified":"Sens {0}, non vérifié",
  "from the phrasebook":"tiré du guide de conversation",
  "composed word by word":"composé mot à mot",
  "from the offline translation":"tiré de la traduction hors ligne",
  "The AI suggested {0}, but {1} was read clearly, so the reading stays. ":"L'IA a proposé {0}, mais {1} a été lu clairement, la lecture est donc conservée. ",
  "This text looks misread{0} — unverified":"Ce texte semble mal lu{0} – non vérifié",
  "Offline translation failed, meaning composed word by word":"Traduction hors ligne échouée, sens composé mot à mot",
  "Translating …":"Traduction …",
  "This text is already saved from this photo.":"Ce texte est déjà enregistré depuis cette photo.",
  "The AI could not be reached":"L'IA est injoignable",
  ". Tap Ask AI to try again.":". Touchez « Demander à l'IA » pour réessayer.",
  "The AI check failed: {0}":"La vérification par l'IA a échoué : {0}",
  "Checking pinyin and meaning …":"Vérification du pinyin et du sens …",
  "Type the text below.":"Saisissez le texte ci-dessous.",
  "Tap a character to change it":"Touchez un caractère pour le changer",
  ", or type the line below":", ou saisissez la ligne ci-dessous",
  "Tap the characters to remove, then Remove.":"Touchez les caractères à retirer, puis Retirer.",
  "Select":"Sélectionner",
  "Remove":"Retirer",
  "Remove {0}":"Retirer {0}",
  "Done":"Terminé",
  "Add a character {0}:":"Ajouter un caractère {0} :",
  "at the start":"au début",
  "at the end":"à la fin",
  "between {0} and {1}":"entre {0} et {1}",
  "Replace {0} with:":"Remplacer {0} par :",
  "Close":"Fermer",
  "No match — draw it or ask the AI.":"Aucune correspondance – dessinez-le ou demandez à l'IA.",
  "Asking the AI …":"Question à l'IA …",
  "Not here? Draw it":"Absent ? Dessinez-le",
  "Add a character:":"Ajouter un caractère :",
  "+ before {0}":"+ avant {0}",
  "+ after {0}":"+ après {0}",
  "The AI has no better idea.":"L'IA n'a pas de meilleure idée.",
  "Draw the character below.":"Dessinez le caractère ci-dessous.",
  "The character in the photo (drag to move, pinch to zoom) — draw it below.":"Le caractère sur la photo (glisser pour déplacer, pincer pour zoomer) – dessinez-le ci-dessous.",
  "the character in the photo":"le caractère sur la photo",
  "Draw all strokes, then tap Done.":"Dessinez tous les traits, puis touchez Terminé.",
  "Undo":"Annuler le trait",
  "Clear":"Effacer",
  "Draw the character first.":"Dessinez d'abord le caractère.",
  "reading …":"lecture …",
  "reading … {0}%":"lecture … {0} %",
  "Read as — tap the right one. Not there? Clear and draw again.":"Lu comme – touchez le bon. Absent ? Effacez et redessinez.",
  "Not recognized — try cleaner, well-separated strokes.":"Non reconnu – essayez des traits plus nets et bien séparés.",
  "saved before the reading was done, and the reading is weak — check text, pinyin and meaning":"enregistrée avant la fin de la lecture, et la lecture est faible – vérifiez le texte, le pinyin et le sens",
  "saved before the reading was done — check text, pinyin and meaning":"enregistrée avant la fin de la lecture – vérifiez le texte, le pinyin et le sens",
  "the new frame could not be read — the old text stays":"le nouveau cadre n'a pas pu être lu – l'ancien texte reste",
  "the reading failed — edit the card or frame the photo again":"la lecture a échoué – modifiez la carte ou recadrez la photo",
  "the reading looks wrong":"la lecture semble fausse",
  "time":"{0} fois","times":"{0} fois","AI check":"{0} vérification par l'IA","AI checks":"{0} vérifications par l'IA",
  "Due":"À faire","capsule:Done":"Faites","Deck":"Cartes","Learn":"Apprendre","Cards":"Cartes","Camera":"Photo","More":"Plus",
  "Language":"Langue","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"Les textes de l'application. Les cartes gardent le chinois, le pinyin et le sens.",
  "Loading …":"Chargement …","No cards yet.":"Pas encore de cartes.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"Photographiez un panneau, un menu ou un emballage sous <b>Photo</b> – ou ajoutez un mot à la main sous <b>Cartes → + Nouvelle</b>.",
  "Take a photo":"Prendre une photo","All clear.":"Tout est fait.","Pulled-forward round finished.":"Tour anticipé terminé.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"Rien à réviser aujourd'hui. Revenez demain – ou avancez les prochaines cartes.",
  "Pull the next cards forward":"Avancer les prochaines cartes","Again":"Encore","Hard":"Difficile","Good":"Bien","Easy":"Facile",
  "⚑ Clear flag":"⚑ Retirer le signalement","⚑ Flag for review":"⚑ Signaler à vérifier","✎ Edit":"✎ Modifier",
  "Tap the character to reveal":"Touchez le caractère pour la réponse",", or the photo for the whole picture":", ou la photo pour l'image entière",
  "← Cards":"← Cartes","Testing from the list":"Test depuis la liste","<10 min":"<10 min","<1 d":"<1 j","1 d":"1 j","{0} d":"{0} j",
  "{0} learned, {1} reviewed this week, streak {2}":"{0} apprises, {1} révisées cette semaine, série de {2}",
  "card":"{0} carte","cards":"{0} cartes","day":"{0} jour","days":"{0} jours","review":"{0} révision","reviews":"{0} révisions","photo":"{0} photo","photos":"{0} photos",
  "AI suggestion waiting":"{0} suggestion de l'IA en attente","AI suggestions waiting":"{0} suggestions de l'IA en attente",
  "Traditional":"Traditionnel","Simplified":"Simplifié","Nothing could be read.":"Rien n'a pu être lu.","Reading the text …":"Lecture du texte …",
  "meaning unverified":"sens non vérifié"," (translation pending)":" (traduction en attente)"," (reading uncertain: {0})":" (lecture incertaine : {0})",
  "Also on another photo":"Aussi sur une autre photo","Also on {0} other photos":"Aussi sur {0} autres photos","Show this photo":"Afficher cette photo","Open this card":"Ouvrir cette carte",
  "Loading the dictionary …":"Chargement du dictionnaire …","not in the dictionary":"absent du dictionnaire","Dictionary not available.":"Dictionnaire indisponible.","Pronounce":"Prononcer",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"Pas de voix chinoise sur ce téléphone – ajoutez-en une dans Réglages, Synthèse vocale.",
  "⚑ Review":"⚑ À vérifier","New":"Nouvelle","Review":"Révision","⚑ Flagged for review":"⚑ Signalée à vérifier",
  "failed {0} times in a row — check text, meaning and photo":"ratée {0} fois de suite – vérifiez le texte, le sens et la photo",
  "AI: this text looks misread":"IA : ce texte semble mal lu","Dismiss":"Ignorer","AI suggestion":"Suggestion de l'IA",": looks right":" : semble correct","Accept":"Accepter","Mark verified":"Marquer comme vérifié","Accept all":"Tout accepter",
  "All cards":"Toutes les cartes","Untagged":"Sans étiquette","Untagged ({0})":"Sans étiquette ({0})",
  "Nothing read":"Rien de lu","Reading …":"Lecture …","AI":"IA","No cards match.":"Aucune carte ne correspond.",
  "No cards yet — take a photo under Camera, or tap + New.":"Pas encore de cartes – prenez une photo sous Photo, ou touchez + Nouvelle.",
  "Search":"Rechercher","+ New":"+ Nouvelle","⚑ Flagged ({0})":"⚑ Signalées ({0})","AI ({0})":"IA ({0})","Unverified ({0})":"Non vérifiées ({0})","{0} of {1}":"{0} sur {1}",
  "due":"à faire","in {0} d":"dans {0} j",
  "Interval {0} d, ease {1}, {2}, next {3}.":"Intervalle {0} j, facilité {1}, {2}, prochaine {3}.","Not studied yet.":"Pas encore étudiée.",
  "Nothing read yet":"Rien de lu encore","unverified":"non vérifié","translation pending":"traduction en attente","reading uncertain":"lecture incertaine",
  "The new frame is being read — the text follows when it is done.":"Le nouveau cadre est en cours de lecture – le texte suivra.",
  "The text, pinyin and meaning follow when the reading is done.":"Le texte, le pinyin et le sens suivront une fois la lecture terminée.",
  "Tap the character to show the answer":"Touchez le caractère pour afficher la réponse","Tap the character to hide the answer":"Touchez le caractère pour masquer la réponse",
  "Test this card":"Tester cette carte","Edit":"Modifier","Delete card":"Supprimer la carte","Delete “{0}”?":"Supprimer « {0} » ?","Delete this card?":"Supprimer cette carte ?",
  "The card and its learning progress will be removed.":"La carte et sa progression seront supprimées.","Delete":"Supprimer","Cancel":"Annuler",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"Vous êtes dans WeChat. Ouvrez cette page dans votre navigateur pour installer l'application et garder vos cartes."
},
es:{
  "Photos stay on this phone. Frame the text — the card is made for you.":"Las fotos se quedan en este teléfono. Encuadra el texto y la tarjeta se crea sola.",
  "Take photo":"Hacer foto",
  "From album":"Del álbum",
  "Processing photo …":"Procesando la foto …",
  "No photos yet.":"Aún no hay fotos.",
  "Inbox ({0})":"Bandeja ({0})",
  "Crop":"Recortar",
  "Turn the frame":"Girar el marco",
  "Draw a frame with your finger over the text — corners resize it, dragging inside moves it, the round handle turns it.":"Dibuja un marco con el dedo sobre el texto: las esquinas cambian el tamaño, arrastrar dentro lo mueve, el asa redonda lo gira.",
  "Finding the text …":"Buscando el texto …",
  "Finding the frame …":"Buscando el marco …",
  "Reading in a moment — drag a corner first if the frame is off.":"Se leerá en un momento; arrastra antes una esquina si el marco no encaja.",
  "The frame the card was cut with — adjust it to read again.":"El marco con el que se recortó la tarjeta: ajústalo para leer de nuevo.",
  " Tap outside the frame for the whole photo.":" Toca fuera del marco para ver la foto entera.",
  " Tap outside the frame to enlarge it again.":" Toca fuera del marco para ampliar de nuevo.",
  "Read now":"Leer ahora",
  "Image only":"Solo la imagen",
  "Frame too small — draw again.":"Marco demasiado pequeño: dibújalo de nuevo.",
  "Reading failed: {0}":"La lectura falló: {0}",
  " still at: {0}":" sigue en: {0}",
  " Still at: {0}":" Sigue en: {0}",
  "Save now":"Guardar ahora",
  "Card saved — the text follows when the reading is done.":"Tarjeta guardada; el texto llegará cuando termine la lectura.",
  "No Chinese characters recognized — frame the characters tightly and try again.":"No se reconoció ningún carácter chino: encuadra los caracteres ajustados e inténtalo de nuevo.",
  "Card saved — {0}.":"Tarjeta guardada: {0}.",
  " Translation pending.":" Traducción pendiente.",
  " Flagged for review.":" Marcada para revisar.",
  "Read as “{0}”. ":"Leído como «{0}». ",
  "Picture taken, the text stays. ":"Imagen tomada, el texto se mantiene. ",
  "Adjust the frame to read again, or save.":"Ajusta el marco para leer de nuevo, o guarda.",
  "Characters":"Caracteres",
  " (traditional, as on the photo)":" (tradicionales, como en la foto)",
  "Pinyin":"Pinyin",
  "Meaning":"Significado",
  "⚑ Flag for review (text, pinyin or meaning looks wrong)":"⚑ Marcar para revisar (el texto, el pinyin o el significado parecen mal)",
  "Note for the reviewer (optional)":"Nota para el revisor (opcional)",
  "Tags":"Etiquetas",
  "Chinese class, HSK 3 …":"Clase de chino, HSK 3 …",
  "Save card":"Guardar tarjeta",
  "Ask AI":"Preguntar a la IA",
  "This reading looks wrong — frame the text tightly and read again, or fix the characters.":"Esta lectura parece incorrecta: encuadra el texto ajustado y lee de nuevo, o corrige los caracteres.",
  " The reading looks uncertain (confidence {0}%) — check the text.":" La lectura parece dudosa (confianza {0} %): revisa el texto.",
  "Only {0} found — if the photo shows more, frame the characters tightly and drag a corner to read again.":"Solo {0}: si la foto muestra más, encuadra los caracteres ajustados y arrastra una esquina para leer de nuevo.",
  "character":"{0} carácter encontrado",
  "characters":"{0} caracteres encontrados",
  "Read from the picture by the AI":"Leído de la imagen por la IA",
  "Meaning {0}, unverified":"Significado {0}, sin verificar",
  "from the phrasebook":"del libro de frases",
  "composed word by word":"compuesto palabra por palabra",
  "from the offline translation":"de la traducción sin conexión",
  "The AI suggested {0}, but {1} was read clearly, so the reading stays. ":"La IA propuso {0}, pero {1} se leyó con claridad, así que la lectura se mantiene. ",
  "This text looks misread{0} — unverified":"Este texto parece mal leído{0}: sin verificar",
  "Offline translation failed, meaning composed word by word":"Falló la traducción sin conexión; significado compuesto palabra por palabra",
  "Translating …":"Traduciendo …",
  "This text is already saved from this photo.":"Este texto ya está guardado desde esta foto.",
  "The AI could not be reached":"No se pudo contactar con la IA",
  ". Tap Ask AI to try again.":". Toca «Preguntar a la IA» para intentarlo de nuevo.",
  "The AI check failed: {0}":"La comprobación de la IA falló: {0}",
  "Checking pinyin and meaning …":"Comprobando pinyin y significado …",
  "Type the text below.":"Escribe el texto abajo.",
  "Tap a character to change it":"Toca un carácter para cambiarlo",
  ", or type the line below":", o escribe la línea abajo",
  "Tap the characters to remove, then Remove.":"Toca los caracteres que quieras quitar y luego Quitar.",
  "Select":"Seleccionar",
  "Remove":"Quitar",
  "Remove {0}":"Quitar {0}",
  "Done":"Listo",
  "Add a character {0}:":"Añadir un carácter {0}:",
  "at the start":"al principio",
  "at the end":"al final",
  "between {0} and {1}":"entre {0} y {1}",
  "Replace {0} with:":"Sustituir {0} por:",
  "Close":"Cerrar",
  "No match — draw it or ask the AI.":"Sin coincidencias: dibújalo o pregunta a la IA.",
  "Asking the AI …":"Preguntando a la IA …",
  "Not here? Draw it":"¿No está? Dibújalo",
  "Add a character:":"Añadir un carácter:",
  "+ before {0}":"+ antes de {0}",
  "+ after {0}":"+ después de {0}",
  "The AI has no better idea.":"La IA no tiene una idea mejor.",
  "Draw the character below.":"Dibuja el carácter abajo.",
  "The character in the photo (drag to move, pinch to zoom) — draw it below.":"El carácter en la foto (arrastra para mover, pellizca para ampliar): dibújalo abajo.",
  "the character in the photo":"el carácter en la foto",
  "Draw all strokes, then tap Done.":"Dibuja todos los trazos y luego toca Listo.",
  "Undo":"Deshacer",
  "Clear":"Borrar",
  "Draw the character first.":"Dibuja primero el carácter.",
  "reading …":"leyendo …",
  "reading … {0}%":"leyendo … {0} %",
  "Read as — tap the right one. Not there? Clear and draw again.":"Leído como: toca el correcto. ¿No está? Borra y dibuja de nuevo.",
  "Not recognized — try cleaner, well-separated strokes.":"No reconocido: prueba con trazos más limpios y separados.",
  "saved before the reading was done, and the reading is weak — check text, pinyin and meaning":"guardada antes de terminar la lectura, y la lectura es débil: revisa el texto, el pinyin y el significado",
  "saved before the reading was done — check text, pinyin and meaning":"guardada antes de terminar la lectura: revisa el texto, el pinyin y el significado",
  "the new frame could not be read — the old text stays":"el nuevo marco no se pudo leer: se mantiene el texto anterior",
  "the reading failed — edit the card or frame the photo again":"la lectura falló: edita la tarjeta o encuadra la foto de nuevo",
  "the reading looks wrong":"la lectura parece incorrecta",
  "time":"{0} vez","times":"{0} veces","AI check":"{0} comprobación de la IA","AI checks":"{0} comprobaciones de la IA",
  "Due":"Pendientes","capsule:Done":"Hechas","Deck":"Tarjetas","Learn":"Aprender","Cards":"Tarjetas","Camera":"Cámara","More":"Más",
  "Language":"Idioma","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"Los textos de la app. Las tarjetas conservan el chino, el pinyin y el significado.",
  "Loading …":"Cargando …","No cards yet.":"Aún no hay tarjetas.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"Fotografía un letrero, una carta o un envase en <b>Cámara</b>, o añade una palabra a mano en <b>Tarjetas → + Nueva</b>.",
  "Take a photo":"Hacer una foto","All clear.":"Todo hecho.","Pulled-forward round finished.":"Ronda adelantada terminada.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"Nada pendiente hoy. Vuelve mañana, o adelanta las siguientes tarjetas.",
  "Pull the next cards forward":"Adelantar las siguientes tarjetas","Again":"Otra vez","Hard":"Difícil","Good":"Bien","Easy":"Fácil",
  "⚑ Clear flag":"⚑ Quitar la marca","⚑ Flag for review":"⚑ Marcar para revisar","✎ Edit":"✎ Editar",
  "Tap the character to reveal":"Toca el carácter para ver la respuesta",", or the photo for the whole picture":", o la foto para ver la imagen entera",
  "← Cards":"← Tarjetas","Testing from the list":"Prueba desde la lista","<10 min":"<10 min","<1 d":"<1 d","1 d":"1 d","{0} d":"{0} d",
  "{0} learned, {1} reviewed this week, streak {2}":"{0} aprendidas, {1} repasadas esta semana, racha de {2}",
  "card":"{0} tarjeta","cards":"{0} tarjetas","day":"{0} día","days":"{0} días","review":"{0} repaso","reviews":"{0} repasos","photo":"{0} foto","photos":"{0} fotos",
  "AI suggestion waiting":"{0} sugerencia de la IA en espera","AI suggestions waiting":"{0} sugerencias de la IA en espera",
  "Traditional":"Tradicional","Simplified":"Simplificado","Nothing could be read.":"No se pudo leer nada.","Reading the text …":"Leyendo el texto …",
  "meaning unverified":"significado sin verificar"," (translation pending)":" (traducción pendiente)"," (reading uncertain: {0})":" (lectura dudosa: {0})",
  "Also on another photo":"También en otra foto","Also on {0} other photos":"También en otras {0} fotos","Show this photo":"Mostrar esta foto","Open this card":"Abrir esta tarjeta",
  "Loading the dictionary …":"Cargando el diccionario …","not in the dictionary":"no está en el diccionario","Dictionary not available.":"Diccionario no disponible.","Pronounce":"Pronunciar",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"Este teléfono no tiene voz china: añade una en Ajustes, Salida de texto a voz.",
  "⚑ Review":"⚑ Revisar","New":"Nueva","Review":"Repaso","⚑ Flagged for review":"⚑ Marcada para revisar",
  "failed {0} times in a row — check text, meaning and photo":"fallada {0} veces seguidas: revisa el texto, el significado y la foto",
  "AI: this text looks misread":"IA: este texto parece mal leído","Dismiss":"Descartar","AI suggestion":"Sugerencia de la IA",": looks right":": parece correcto","Accept":"Aceptar","Mark verified":"Marcar como verificada","Accept all":"Aceptar todas",
  "All cards":"Todas las tarjetas","Untagged":"Sin etiqueta","Untagged ({0})":"Sin etiqueta ({0})",
  "Nothing read":"Nada leído","Reading …":"Leyendo …","AI":"IA","No cards match.":"Ninguna tarjeta coincide.",
  "No cards yet — take a photo under Camera, or tap + New.":"Aún no hay tarjetas: haz una foto en Cámara o toca + Nueva.",
  "Search":"Buscar","+ New":"+ Nueva","⚑ Flagged ({0})":"⚑ Marcadas ({0})","AI ({0})":"IA ({0})","Unverified ({0})":"Sin verificar ({0})","{0} of {1}":"{0} de {1}",
  "due":"pendiente","in {0} d":"en {0} d",
  "Interval {0} d, ease {1}, {2}, next {3}.":"Intervalo {0} d, facilidad {1}, {2}, próximo {3}.","Not studied yet.":"Aún no estudiada.",
  "Nothing read yet":"Aún nada leído","unverified":"sin verificar","translation pending":"traducción pendiente","reading uncertain":"lectura dudosa",
  "The new frame is being read — the text follows when it is done.":"Se está leyendo el nuevo recorte: el texto llegará cuando termine.",
  "The text, pinyin and meaning follow when the reading is done.":"El texto, el pinyin y el significado llegarán cuando termine la lectura.",
  "Tap the character to show the answer":"Toca el carácter para mostrar la respuesta","Tap the character to hide the answer":"Toca el carácter para ocultar la respuesta",
  "Test this card":"Probar esta tarjeta","Edit":"Editar","Delete card":"Eliminar tarjeta","Delete “{0}”?":"¿Eliminar «{0}»?","Delete this card?":"¿Eliminar esta tarjeta?",
  "The card and its learning progress will be removed.":"Se eliminarán la tarjeta y su progreso.","Delete":"Eliminar","Cancel":"Cancelar",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"Estás dentro de WeChat. Abre esta página en tu navegador para instalar la app y conservar tus tarjetas."
},
ja:{
  "Photos stay on this phone. Frame the text — the card is made for you.":"写真はこの端末に残ります。文字を枠で囲むと、カードが作られます。",
  "Take photo":"写真を撮る",
  "From album":"アルバムから",
  "Processing photo …":"写真を処理中 …",
  "No photos yet.":"写真はまだありません。",
  "Inbox ({0})":"受信 ({0})",
  "Crop":"切り抜き",
  "Turn the frame":"枠を回す",
  "Draw a frame with your finger over the text — corners resize it, dragging inside moves it, the round handle turns it.":"指で文字の上に枠を描いてください。角で大きさを変え、中をドラッグして動かし、丸いつまみで回します。",
  "Finding the text …":"文字を探しています …",
  "Finding the frame …":"枠を探しています …",
  "Reading in a moment — drag a corner first if the frame is off.":"まもなく読み取ります。枠がずれていれば先に角をドラッグしてください。",
  "The frame the card was cut with — adjust it to read again.":"カードを切り抜いた枠です。調整すると読み直します。",
  " Tap outside the frame for the whole photo.":" 枠の外をタップすると写真全体が見られます。",
  " Tap outside the frame to enlarge it again.":" 枠の外をタップすると再び拡大します。",
  "Read now":"今すぐ読む",
  "Image only":"画像のみ",
  "Frame too small — draw again.":"枠が小さすぎます。描き直してください。",
  "Reading failed: {0}":"読み取りに失敗: {0}",
  " still at: {0}":" まだここです: {0}",
  " Still at: {0}":" まだここです: {0}",
  "Save now":"今すぐ保存",
  "Card saved — the text follows when the reading is done.":"カードを保存しました。読み取りが終わると文字が入ります。",
  "No Chinese characters recognized — frame the characters tightly and try again.":"漢字を認識できませんでした。文字をぴったり囲んでもう一度お試しください。",
  "Card saved — {0}.":"カードを保存しました: {0}",
  " Translation pending.":" 翻訳待ちです。",
  " Flagged for review.":" 要確認の印を付けました。",
  "Read as “{0}”. ":"「{0}」と読み取りました。",
  "Picture taken, the text stays. ":"画像を取り込みました。文字はそのままです。",
  "Adjust the frame to read again, or save.":"枠を調整すると読み直します。または保存してください。",
  "Characters":"文字",
  " (traditional, as on the photo)":"（繁体字、写真のとおり）",
  "Pinyin":"ピンイン",
  "Meaning":"意味",
  "⚑ Flag for review (text, pinyin or meaning looks wrong)":"⚑ 要確認の印（文字・ピンイン・意味に疑問がある）",
  "Note for the reviewer (optional)":"確認者へのメモ（任意）",
  "Tags":"タグ",
  "Chinese class, HSK 3 …":"中国語教室、HSK 3 …",
  "Save card":"カードを保存",
  "Ask AI":"AIに聞く",
  "This reading looks wrong — frame the text tightly and read again, or fix the characters.":"この読み取りは誤りのようです。文字をぴったり囲んで読み直すか、文字を直してください。",
  " The reading looks uncertain (confidence {0}%) — check the text.":" 読み取りが不確かです（確度 {0}%）。文字を確認してください。",
  "Only {0} found — if the photo shows more, frame the characters tightly and drag a corner to read again.":"{0}しか見つかりません。写真にもっとあれば、文字をぴったり囲んで角をドラッグし、読み直してください。",
  "character":"{0}文字",
  "characters":"{0}文字",
  "Read from the picture by the AI":"AIが画像から読み取り",
  "Meaning {0}, unverified":"意味は{0}、未確認",
  "from the phrasebook":"会話集から",
  "composed word by word":"単語ごとにつなげたもの",
  "from the offline translation":"オフライン翻訳から",
  "The AI suggested {0}, but {1} was read clearly, so the reading stays. ":"AIは{0}を提案しましたが、{1}ははっきり読めているので読み取りを保ちます。",
  "This text looks misread{0} — unverified":"この文字は読み間違いのようです{0}。未確認",
  "Offline translation failed, meaning composed word by word":"オフライン翻訳に失敗。意味は単語ごとにつなげたもの",
  "Translating …":"翻訳中 …",
  "This text is already saved from this photo.":"この文字はこの写真からすでに保存されています。",
  "The AI could not be reached":"AIに接続できませんでした",
  ". Tap Ask AI to try again.":"。「AIに聞く」をタップして再試行してください。",
  "The AI check failed: {0}":"AIの確認に失敗: {0}",
  "Checking pinyin and meaning …":"ピンインと意味を確認中 …",
  "Type the text below.":"下に文字を入力してください。",
  "Tap a character to change it":"文字をタップすると変更できます",
  ", or type the line below":"。下の行に入力もできます",
  "Tap the characters to remove, then Remove.":"削除する文字をタップし、「削除」を押してください。",
  "Select":"選択",
  "Remove":"削除",
  "Remove {0}":"{0}を削除",
  "Done":"完了",
  "Add a character {0}:":"{0}に文字を追加:",
  "at the start":"先頭",
  "at the end":"末尾",
  "between {0} and {1}":"{0}と{1}の間",
  "Replace {0} with:":"{0}を置き換え:",
  "Close":"閉じる",
  "No match — draw it or ask the AI.":"候補がありません。描くか、AIに聞いてください。",
  "Asking the AI …":"AIに聞いています …",
  "Not here? Draw it":"ない？ 描く",
  "Add a character:":"文字を追加:",
  "+ before {0}":"+ {0}の前",
  "+ after {0}":"+ {0}の後",
  "The AI has no better idea.":"AIにも良い案がありません。",
  "Draw the character below.":"下に文字を描いてください。",
  "The character in the photo (drag to move, pinch to zoom) — draw it below.":"写真の文字（ドラッグで移動、ピンチで拡大）。下に描いてください。",
  "the character in the photo":"写真の文字",
  "Draw all strokes, then tap Done.":"すべての画を描いてから「完了」をタップしてください。",
  "Undo":"元に戻す",
  "Clear":"消去",
  "Draw the character first.":"先に文字を描いてください。",
  "reading …":"読み取り中 …",
  "reading … {0}%":"読み取り中 … {0}%",
  "Read as — tap the right one. Not there? Clear and draw again.":"読み取り結果です。正しいものをタップしてください。なければ消去して描き直してください。",
  "Not recognized — try cleaner, well-separated strokes.":"認識できませんでした。はっきり離した画で描いてみてください。",
  "saved before the reading was done, and the reading is weak — check text, pinyin and meaning":"読み取り完了前に保存され、読み取りも弱い — 文字・ピンイン・意味を確認してください",
  "saved before the reading was done — check text, pinyin and meaning":"読み取り完了前に保存 — 文字・ピンイン・意味を確認してください",
  "the new frame could not be read — the old text stays":"新しい枠を読み取れませんでした — 元の文字のままです",
  "the reading failed — edit the card or frame the photo again":"読み取りに失敗 — カードを編集するか写真を囲み直してください",
  "the reading looks wrong":"読み取りが誤りのようです",
  "time":"{0}回","times":"{0}回","AI check":"AI確認{0}回","AI checks":"AI確認{0}回",
  "Due":"今日","capsule:Done":"済み","Deck":"カード","Learn":"学習","Cards":"カード","Camera":"カメラ","More":"その他",
  "Language":"言語","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"アプリの表示言語です。カードの中国語・ピンイン・意味は変わりません。",
  "Loading …":"読み込み中 …","No cards yet.":"カードはまだありません。",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"<b>カメラ</b>で看板・メニュー・パッケージを撮影するか、<b>カード → + 新規</b>で単語を手入力してください。",
  "Take a photo":"写真を撮る","All clear.":"今日の分は終わりました。","Pulled-forward round finished.":"前倒しの復習が終わりました。",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"今日の復習はありません。明日また来るか、次のカードを前倒しできます。",
  "Pull the next cards forward":"次のカードを前倒しする","Again":"もう一度","Hard":"難しい","Good":"普通","Easy":"簡単",
  "⚑ Clear flag":"⚑ 印を外す","⚑ Flag for review":"⚑ 要確認の印","✎ Edit":"✎ 編集",
  "Tap the character to reveal":"文字をタップすると答えが表示されます",", or the photo for the whole picture":"。写真をタップすると全体が見られます",
  "← Cards":"← カード","Testing from the list":"一覧からテスト中","<10 min":"<10分","<1 d":"<1日","1 d":"1日","{0} d":"{0}日",
  "{0} learned, {1} reviewed this week, streak {2}":"習得 {0}、今週の復習 {1}、連続 {2}",
  "card":"カード{0}枚","cards":"カード{0}枚","day":"{0}日","days":"{0}日","review":"{0}回","reviews":"{0}回","photo":"写真{0}枚","photos":"写真{0}枚",
  "AI suggestion waiting":"AIの提案 {0} 件","AI suggestions waiting":"AIの提案 {0} 件",
  "Traditional":"繁体字","Simplified":"簡体字","Nothing could be read.":"何も読み取れませんでした。","Reading the text …":"文字を読み取り中 …",
  "meaning unverified":"意味は未確認"," (translation pending)":"（翻訳待ち）"," (reading uncertain: {0})":"（読み取りが不確か: {0}）",
  "Also on another photo":"別の写真にもあります","Also on {0} other photos":"他の {0} 枚の写真にもあります","Show this photo":"この写真を表示","Open this card":"このカードを開く",
  "Loading the dictionary …":"辞書を読み込み中 …","not in the dictionary":"辞書にありません","Dictionary not available.":"辞書を使えません。","Pronounce":"発音",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"この端末に中国語の音声がありません。設定の「テキスト読み上げ」で追加してください。",
  "⚑ Review":"⚑ 要確認","New":"新規","Review":"復習","⚑ Flagged for review":"⚑ 要確認の印付き",
  "failed {0} times in a row — check text, meaning and photo":"{0} 回続けて不正解 — 文字・意味・写真を確認してください",
  "AI: this text looks misread":"AI: この文字は読み間違いのようです","Dismiss":"閉じる","AI suggestion":"AIの提案",": looks right":": 問題なさそうです","Accept":"採用","Mark verified":"確認済みにする","Accept all":"すべて採用",
  "All cards":"すべてのカード","Untagged":"タグなし","Untagged ({0})":"タグなし ({0})",
  "Nothing read":"読み取れず","Reading …":"読み取り中 …","AI":"AI","No cards match.":"該当するカードがありません。",
  "No cards yet — take a photo under Camera, or tap + New.":"カードはまだありません。カメラで撮影するか、+ 新規をタップしてください。",
  "Search":"検索","+ New":"+ 新規","⚑ Flagged ({0})":"⚑ 要確認 ({0})","AI ({0})":"AI ({0})","Unverified ({0})":"未確認 ({0})","{0} of {1}":"{0} / {1}",
  "due":"今日","in {0} d":"{0}日後",
  "Interval {0} d, ease {1}, {2}, next {3}.":"間隔 {0} 日、易しさ {1}、{2}、次回 {3}。","Not studied yet.":"まだ学習していません。",
  "Nothing read yet":"まだ読み取れていません","unverified":"未確認","translation pending":"翻訳待ち","reading uncertain":"読み取りが不確か",
  "The new frame is being read — the text follows when it is done.":"新しい範囲を読み取り中です。終わると文字が入ります。",
  "The text, pinyin and meaning follow when the reading is done.":"読み取りが終わると文字・ピンイン・意味が入ります。",
  "Tap the character to show the answer":"文字をタップすると答えが表示されます","Tap the character to hide the answer":"文字をタップすると答えが隠れます",
  "Test this card":"このカードをテスト","Edit":"編集","Delete card":"カードを削除","Delete “{0}”?":"「{0}」を削除しますか？","Delete this card?":"このカードを削除しますか？",
  "The card and its learning progress will be removed.":"カードと学習記録が削除されます。","Delete":"削除","Cancel":"キャンセル",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"WeChat 内で開いています。アプリをインストールしてカードを残すには、ブラウザでこのページを開いてください。"
},
ko:{
  "Photos stay on this phone. Frame the text — the card is made for you.":"사진은 이 기기에만 남습니다. 글자를 틀로 감싸면 카드가 만들어집니다.",
  "Take photo":"사진 찍기",
  "From album":"앨범에서",
  "Processing photo …":"사진 처리 중 …",
  "No photos yet.":"아직 사진이 없습니다.",
  "Inbox ({0})":"받은 사진 ({0})",
  "Crop":"자르기",
  "Turn the frame":"틀 돌리기",
  "Draw a frame with your finger over the text — corners resize it, dragging inside moves it, the round handle turns it.":"손가락으로 글자 위에 틀을 그리세요. 모서리로 크기를 바꾸고, 안쪽을 끌어 옮기고, 둥근 손잡이로 돌립니다.",
  "Finding the text …":"글자를 찾는 중 …",
  "Finding the frame …":"틀을 찾는 중 …",
  "Reading in a moment — drag a corner first if the frame is off.":"곧 읽습니다. 틀이 어긋났으면 먼저 모서리를 끌어 맞추세요.",
  "The frame the card was cut with — adjust it to read again.":"카드를 잘라낸 틀입니다. 조정하면 다시 읽습니다.",
  " Tap outside the frame for the whole photo.":" 틀 밖을 누르면 사진 전체가 보입니다.",
  " Tap outside the frame to enlarge it again.":" 틀 밖을 누르면 다시 확대됩니다.",
  "Read now":"지금 읽기",
  "Image only":"이미지만",
  "Frame too small — draw again.":"틀이 너무 작습니다. 다시 그리세요.",
  "Reading failed: {0}":"읽기 실패: {0}",
  " still at: {0}":" 아직 여기: {0}",
  " Still at: {0}":" 아직 여기: {0}",
  "Save now":"지금 저장",
  "Card saved — the text follows when the reading is done.":"카드를 저장했습니다. 읽기가 끝나면 글자가 채워집니다.",
  "No Chinese characters recognized — frame the characters tightly and try again.":"한자를 인식하지 못했습니다. 글자를 딱 맞게 감싸고 다시 시도하세요.",
  "Card saved — {0}.":"카드를 저장했습니다: {0}",
  " Translation pending.":" 번역 대기 중.",
  " Flagged for review.":" 검토 표시됨.",
  "Read as “{0}”. ":"“{0}”(으)로 읽었습니다. ",
  "Picture taken, the text stays. ":"이미지를 가져왔습니다. 글자는 그대로입니다. ",
  "Adjust the frame to read again, or save.":"틀을 조정하면 다시 읽습니다. 또는 저장하세요.",
  "Characters":"글자",
  " (traditional, as on the photo)":" (번체자, 사진과 같음)",
  "Pinyin":"병음",
  "Meaning":"뜻",
  "⚑ Flag for review (text, pinyin or meaning looks wrong)":"⚑ 검토 표시 (글자, 병음, 뜻이 틀린 것 같음)",
  "Note for the reviewer (optional)":"검토자에게 남길 메모 (선택)",
  "Tags":"태그",
  "Chinese class, HSK 3 …":"중국어 수업, HSK 3 …",
  "Save card":"카드 저장",
  "Ask AI":"AI에게 묻기",
  "This reading looks wrong — frame the text tightly and read again, or fix the characters.":"이 읽기는 틀린 것 같습니다. 글자를 딱 맞게 감싸고 다시 읽거나 글자를 고치세요.",
  " The reading looks uncertain (confidence {0}%) — check the text.":" 읽기가 불확실합니다 (확신도 {0}%). 글자를 확인하세요.",
  "Only {0} found — if the photo shows more, frame the characters tightly and drag a corner to read again.":"{0}만 찾았습니다. 사진에 더 있다면 글자를 딱 맞게 감싸고 모서리를 끌어 다시 읽으세요.",
  "character":"{0}글자",
  "characters":"{0}글자",
  "Read from the picture by the AI":"AI가 사진에서 읽음",
  "Meaning {0}, unverified":"뜻은 {0}, 미확인",
  "from the phrasebook":"회화집에서",
  "composed word by word":"단어별로 이어 붙임",
  "from the offline translation":"오프라인 번역에서",
  "The AI suggested {0}, but {1} was read clearly, so the reading stays. ":"AI는 {0}을(를) 제안했지만 {1}이(가) 분명히 읽혔으므로 읽기를 유지합니다. ",
  "This text looks misread{0} — unverified":"이 글자는 잘못 읽힌 것 같습니다{0} — 미확인",
  "Offline translation failed, meaning composed word by word":"오프라인 번역 실패, 뜻은 단어별로 이어 붙임",
  "Translating …":"번역 중 …",
  "This text is already saved from this photo.":"이 글자는 이 사진에서 이미 저장되었습니다.",
  "The AI could not be reached":"AI에 연결할 수 없습니다",
  ". Tap Ask AI to try again.":". 'AI에게 묻기'를 눌러 다시 시도하세요.",
  "The AI check failed: {0}":"AI 확인 실패: {0}",
  "Checking pinyin and meaning …":"병음과 뜻을 확인하는 중 …",
  "Type the text below.":"아래에 글자를 입력하세요.",
  "Tap a character to change it":"글자를 누르면 바꿀 수 있습니다",
  ", or type the line below":". 아래 줄에 입력해도 됩니다",
  "Tap the characters to remove, then Remove.":"지울 글자를 누른 다음 '제거'를 누르세요.",
  "Select":"선택",
  "Remove":"제거",
  "Remove {0}":"{0} 제거",
  "Done":"완료",
  "Add a character {0}:":"{0}에 글자 추가:",
  "at the start":"맨 앞",
  "at the end":"맨 뒤",
  "between {0} and {1}":"{0}과(와) {1} 사이",
  "Replace {0} with:":"{0}을(를) 바꾸기:",
  "Close":"닫기",
  "No match — draw it or ask the AI.":"후보가 없습니다. 직접 그리거나 AI에게 물어보세요.",
  "Asking the AI …":"AI에게 묻는 중 …",
  "Not here? Draw it":"없나요? 그리기",
  "Add a character:":"글자 추가:",
  "+ before {0}":"+ {0} 앞에",
  "+ after {0}":"+ {0} 뒤에",
  "The AI has no better idea.":"AI도 더 나은 답이 없습니다.",
  "Draw the character below.":"아래에 글자를 그리세요.",
  "The character in the photo (drag to move, pinch to zoom) — draw it below.":"사진 속 글자 (끌어서 이동, 두 손가락으로 확대). 아래에 그리세요.",
  "the character in the photo":"사진 속 글자",
  "Draw all strokes, then tap Done.":"모든 획을 그린 다음 '완료'를 누르세요.",
  "Undo":"되돌리기",
  "Clear":"지우기",
  "Draw the character first.":"먼저 글자를 그리세요.",
  "reading …":"읽는 중 …",
  "reading … {0}%":"읽는 중 … {0}%",
  "Read as — tap the right one. Not there? Clear and draw again.":"읽은 결과입니다. 맞는 것을 누르세요. 없으면 지우고 다시 그리세요.",
  "Not recognized — try cleaner, well-separated strokes.":"인식하지 못했습니다. 획을 또렷하고 떨어지게 그려 보세요.",
  "saved before the reading was done, and the reading is weak — check text, pinyin and meaning":"읽기가 끝나기 전에 저장되었고 읽기도 약함 — 글자, 병음, 뜻을 확인하세요",
  "saved before the reading was done — check text, pinyin and meaning":"읽기가 끝나기 전에 저장됨 — 글자, 병음, 뜻을 확인하세요",
  "the new frame could not be read — the old text stays":"새 틀을 읽지 못함 — 이전 글자를 유지합니다",
  "the reading failed — edit the card or frame the photo again":"읽기 실패 — 카드를 편집하거나 사진을 다시 감싸세요",
  "the reading looks wrong":"읽기가 틀린 것 같습니다",
  "time":"{0}번","times":"{0}번","AI check":"AI 확인 {0}회","AI checks":"AI 확인 {0}회",
  "Due":"오늘","capsule:Done":"완료","Deck":"카드","Learn":"학습","Cards":"카드","Camera":"카메라","More":"더보기",
  "Language":"언어","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"앱의 표시 언어입니다. 카드의 중국어, 병음, 뜻은 그대로입니다.",
  "Loading …":"불러오는 중 …","No cards yet.":"아직 카드가 없습니다.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"<b>카메라</b>에서 간판, 메뉴, 포장을 찍거나 <b>카드 → + 새로 만들기</b>에서 단어를 직접 입력하세요.",
  "Take a photo":"사진 찍기","All clear.":"오늘 분량을 마쳤습니다.","Pulled-forward round finished.":"앞당긴 복습을 마쳤습니다.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"오늘 복습할 카드가 없습니다. 내일 다시 오거나 다음 카드를 앞당길 수 있습니다.",
  "Pull the next cards forward":"다음 카드 앞당기기","Again":"다시","Hard":"어려움","Good":"보통","Easy":"쉬움",
  "⚑ Clear flag":"⚑ 표시 지우기","⚑ Flag for review":"⚑ 검토 표시","✎ Edit":"✎ 편집",
  "Tap the character to reveal":"글자를 누르면 답이 보입니다",", or the photo for the whole picture":". 사진을 누르면 전체 사진이 보입니다",
  "← Cards":"← 카드","Testing from the list":"목록에서 테스트 중","<10 min":"<10분","<1 d":"<1일","1 d":"1일","{0} d":"{0}일",
  "{0} learned, {1} reviewed this week, streak {2}":"학습 {0}, 이번 주 복습 {1}, 연속 {2}",
  "card":"카드 {0}장","cards":"카드 {0}장","day":"{0}일","days":"{0}일","review":"{0}회","reviews":"{0}회","photo":"사진 {0}장","photos":"사진 {0}장",
  "AI suggestion waiting":"AI 제안 {0}개 대기 중","AI suggestions waiting":"AI 제안 {0}개 대기 중",
  "Traditional":"번체자","Simplified":"간체자","Nothing could be read.":"아무것도 읽지 못했습니다.","Reading the text …":"글자를 읽는 중 …",
  "meaning unverified":"뜻 미확인"," (translation pending)":" (번역 대기)"," (reading uncertain: {0})":" (읽기 불확실: {0})",
  "Also on another photo":"다른 사진에도 있음","Also on {0} other photos":"다른 사진 {0}장에도 있음","Show this photo":"이 사진 보기","Open this card":"이 카드 열기",
  "Loading the dictionary …":"사전을 불러오는 중 …","not in the dictionary":"사전에 없음","Dictionary not available.":"사전을 사용할 수 없습니다.","Pronounce":"발음",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"이 기기에 중국어 음성이 없습니다. 설정의 '텍스트 음성 변환'에서 추가하세요.",
  "⚑ Review":"⚑ 검토","New":"새 카드","Review":"복습","⚑ Flagged for review":"⚑ 검토 표시됨",
  "failed {0} times in a row — check text, meaning and photo":"{0}회 연속 틀림 — 글자, 뜻, 사진을 확인하세요",
  "AI: this text looks misread":"AI: 이 글자는 잘못 읽힌 것 같습니다","Dismiss":"닫기","AI suggestion":"AI 제안",": looks right":": 맞는 것 같습니다","Accept":"적용","Mark verified":"확인됨으로 표시","Accept all":"모두 적용",
  "All cards":"모든 카드","Untagged":"태그 없음","Untagged ({0})":"태그 없음 ({0})",
  "Nothing read":"읽지 못함","Reading …":"읽는 중 …","AI":"AI","No cards match.":"일치하는 카드가 없습니다.",
  "No cards yet — take a photo under Camera, or tap + New.":"아직 카드가 없습니다. 카메라에서 사진을 찍거나 + 새로 만들기를 누르세요.",
  "Search":"검색","+ New":"+ 새로 만들기","⚑ Flagged ({0})":"⚑ 표시됨 ({0})","AI ({0})":"AI ({0})","Unverified ({0})":"미확인 ({0})","{0} of {1}":"{0} / {1}",
  "due":"오늘","in {0} d":"{0}일 후",
  "Interval {0} d, ease {1}, {2}, next {3}.":"간격 {0}일, 난이도 계수 {1}, {2}, 다음 {3}.","Not studied yet.":"아직 학습하지 않았습니다.",
  "Nothing read yet":"아직 읽지 못함","unverified":"미확인","translation pending":"번역 대기","reading uncertain":"읽기 불확실",
  "The new frame is being read — the text follows when it is done.":"새 영역을 읽는 중입니다. 끝나면 글자가 채워집니다.",
  "The text, pinyin and meaning follow when the reading is done.":"읽기가 끝나면 글자, 병음, 뜻이 채워집니다.",
  "Tap the character to show the answer":"글자를 누르면 답이 보입니다","Tap the character to hide the answer":"글자를 누르면 답이 숨겨집니다",
  "Test this card":"이 카드 테스트","Edit":"편집","Delete card":"카드 삭제","Delete “{0}”?":"“{0}”을(를) 삭제할까요?","Delete this card?":"이 카드를 삭제할까요?",
  "The card and its learning progress will be removed.":"카드와 학습 기록이 삭제됩니다.","Delete":"삭제","Cancel":"취소",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"WeChat 안에서 열려 있습니다. 앱을 설치하고 카드를 보관하려면 브라우저에서 이 페이지를 여세요."
}
};
