/* 识字 Zeichentrainer — the app's own texts in other languages (v253, H: "Multi language UI and translations").
   English is the key: t("Save card") looks the sentence up in the current language and falls back to the English text
   itself, so a missing translation shows English, never a key. {0}, {1} … are filled in by t(); a count word ("card",
   "cards") may carry the number as {0} where the language puts it elsewhere ("カード{0}枚"). The learning content stays
   Chinese, pinyin and the meaning; the owner's tools (Diagnostics, All users, Feedback, the usage report) stay English.
   To add a language: one more entry in LANGS and one more column below. */
const LANGS=[["en","English"],["de","Deutsch"],["fr","Français"],["es","Español"],["ja","日本語"],["ko","한국어"]];
const LANG_LOCALE={en:"en-GB",de:"de-DE",fr:"fr-FR",es:"es-ES",ja:"ja-JP",ko:"ko-KR"};
let LANG="en";
function langDefault(){ const l=String(navigator.language||"").toLowerCase().slice(0,2); return LANGS.some(([c])=>c===l)?l:"en"; }
function t(key,...args){ const d=L10N[LANG], s=d&&d[key]!=null?d[key]:key; return args.length?s.replace(/\{(\d)\}/g,(m,i)=>args[+i]!=null?args[+i]:m):s; }
/* a count with its word: nOf(3,"card") → "3 cards" / "3 Karten" / "カード3枚"; pl = an irregular plural key */
function nOf(n,w,pl){ n=n||0; const key=n===1?w:(pl||w+"s"), d=L10N[LANG], tr=d&&d[key]!=null?d[key]:key; return tr.includes("{0}")?tr.replace("{0}",n):`${n} ${tr}`; }
const L10N={
de:{
  "time":"{0}-mal","times":"{0}-mal","AI check":"{0} KI-Prüfung","AI checks":"{0} KI-Prüfungen",
  "Due":"Fällig","Done":"Fertig","Deck":"Karten","Learn":"Lernen","Cards":"Karten","Camera":"Kamera","More":"Mehr",
  "Language":"Sprache","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"Die Texte der App. Die Karten behalten Chinesisch, Pinyin und Bedeutung.",
  "Loading …":"Lädt …","No cards yet.":"Noch keine Karten.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"Fotografiere ein Schild, eine Speisekarte oder eine Verpackung unter <b>Kamera</b> – oder trage ein Wort von Hand ein unter <b>Karten → + Neu</b>.",
  "Take a photo":"Foto aufnehmen","All clear.":"Alles erledigt.","Pulled-forward round finished.":"Vorgezogene Runde beendet.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"Heute ist nichts fällig. Komm morgen wieder – oder zieh die nächsten Karten vor.",
  "Pull the next cards forward":"Nächste Karten vorziehen","Again":"Nochmal","Hard":"Schwer","Good":"Gut","Easy":"Leicht",
  "⚑ Clear flag":"⚑ Markierung entfernen","⚑ Flag for review":"⚑ Zur Prüfung markieren","✎ Edit":"✎ Bearbeiten",
  "Tap the character to reveal":"Tippe auf das Zeichen für die Antwort",", or the photo for the whole picture":", oder auf das Foto für das ganze Bild",
  "← Cards":"← Karten","Testing from the list":"Test aus der Liste","<10 min":"<10 Min","<1 d":"<1 T","1 d":"1 T","{0} d":"{0} T",
  "{0} learned, {1} reviewed this week, streak {2}":"{0} gelernt, {1} diese Woche wiederholt, Serie {2}",
  "card":"{0} Karte","cards":"{0} Karten","day":"{0} Tag","days":"{0} Tage","review":"{0} Wiederholung","reviews":"{0} Wiederholungen","photo":"{0} Foto","photos":"{0} Fotos",
  "AI suggestion waiting":"{0} KI-Vorschlag wartet","AI suggestions waiting":"{0} KI-Vorschläge warten",
  "Traditional":"Langzeichen","Simplified":"Kurzzeichen","Nothing could be read.":"Es konnte nichts gelesen werden.","Reading the text …":"Text wird gelesen …",
  "meaning unverified":"Bedeutung ungeprüft"," (translation pending)":" (Übersetzung ausstehend)"," (reading uncertain: {0})":" (Lesung unsicher: {0})",
  "Also on another photo":"Auch auf einem anderen Foto","Also on {0} other photos":"Auch auf {0} anderen Fotos","Show this photo":"Dieses Foto zeigen","Open this card":"Diese Karte öffnen",
  "Loading the dictionary …":"Wörterbuch wird geladen …","not in the dictionary":"nicht im Wörterbuch","Dictionary not available.":"Wörterbuch nicht verfügbar.","Pronounce":"Aussprechen",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"Keine chinesische Stimme auf diesem Telefon – füge eine hinzu unter Einstellungen, Text-in-Sprache.",
  "⚑ Review":"⚑ Prüfen","New":"Neu","Review":"Wiederholen","⚑ Flagged for review":"⚑ Zur Prüfung markiert",
  "failed {0} times in a row — check text, meaning and photo":"{0}-mal hintereinander nicht gewusst – Text, Bedeutung und Foto prüfen",
  "AI: this text looks misread":"KI: dieser Text scheint falsch gelesen","Dismiss":"Verwerfen","AI suggestion":"KI-Vorschlag",": looks right":": sieht richtig aus","Accept":"Übernehmen","Mark verified":"Als geprüft markieren","Accept all":"Alle übernehmen",
  "All cards":"Alle Karten","Untagged":"Ohne Tag","Untagged ({0})":"Ohne Tag ({0})",
  "Nothing read":"Nichts gelesen","Reading …":"Wird gelesen …","AI":"KI","No cards match.":"Keine Karte passt.",
  "No cards yet — take a photo under Camera, or tap + New.":"Noch keine Karten – nimm ein Foto auf unter Kamera, oder tippe auf + Neu.",
  "Search":"Suchen","+ New":"+ Neu","⚑ Flagged ({0})":"⚑ Markiert ({0})","AI ({0})":"KI ({0})","Unverified ({0})":"Ungeprüft ({0})","{0} of {1}":"{0} von {1}",
  "due":"fällig","in {0} d":"in {0} T",
  "Interval {0} d, ease {1}, {2}, next {3}.":"Intervall {0} T, Leichtigkeit {1}, {2}, nächste {3}.","Not studied yet.":"Noch nicht gelernt.",
  "Nothing read yet":"Noch nichts gelesen","unverified":"ungeprüft","translation pending":"Übersetzung ausstehend","reading uncertain":"Lesung unsicher",
  "The new frame is being read — the text follows when it is done.":"Der neue Ausschnitt wird gelesen – der Text folgt, sobald es fertig ist.",
  "The text, pinyin and meaning follow when the reading is done.":"Text, Pinyin und Bedeutung folgen, sobald das Lesen fertig ist.",
  "Tap the character to show the answer":"Tippe auf das Zeichen für die Antwort","Tap the character to hide the answer":"Tippe auf das Zeichen, um die Antwort zu verbergen",
  "Test this card":"Diese Karte testen","Edit":"Bearbeiten","Delete card":"Karte löschen","Delete “{0}”?":"„{0}“ löschen?","Delete this card?":"Diese Karte löschen?",
  "The card and its learning progress will be removed.":"Die Karte und ihr Lernfortschritt werden entfernt.","Delete":"Löschen","Cancel":"Abbrechen",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"Du bist in WeChat. Öffne diese Seite im Browser, um die App zu installieren und deine Karten zu behalten."
},
fr:{
  "time":"{0} fois","times":"{0} fois","AI check":"{0} vérification par l'IA","AI checks":"{0} vérifications par l'IA",
  "Due":"À faire","Done":"Fait","Deck":"Cartes","Learn":"Apprendre","Cards":"Cartes","Camera":"Photo","More":"Plus",
  "Language":"Langue","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"Les textes de l'application. Les cartes gardent le chinois, le pinyin et le sens.",
  "Loading …":"Chargement …","No cards yet.":"Pas encore de cartes.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"Photographiez un panneau, un menu ou un emballage sous <b>Photo</b> – ou ajoutez un mot à la main sous <b>Cartes → + Nouvelle</b>.",
  "Take a photo":"Prendre une photo","All clear.":"Tout est fait.","Pulled-forward round finished.":"Tour anticipé terminé.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"Rien à réviser aujourd'hui. Revenez demain – ou avancez les prochaines cartes.",
  "Pull the next cards forward":"Avancer les prochaines cartes","Again":"Encore","Hard":"Difficile","Good":"Bien","Easy":"Facile",
  "⚑ Clear flag":"⚑ Retirer le signalement","⚑ Flag for review":"⚑ Signaler à vérifier","✎ Edit":"✎ Modifier",
  "Tap the character to reveal":"Touchez le caractère pour la réponse",", or the photo for the whole picture":", ou la photo pour l'image entière",
  "← Cards":"← Cartes","Testing from the list":"Test depuis la liste","<10 min":"<10 min","<1 d":"<1 j","1 d":"1 j","{0} d":"{0} j",
  "{0} learned, {1} reviewed this week, streak {2}":"{0} apprises, {1} révisées cette semaine, série de {2}",
  "card":"{0} carte","cards":"{0} cartes","day":"{0} jour","days":"{0} jours","review":"{0} révision","reviews":"{0} révisions","photo":"{0} photo","photos":"{0} photos",
  "AI suggestion waiting":"{0} suggestion de l'IA en attente","AI suggestions waiting":"{0} suggestions de l'IA en attente",
  "Traditional":"Traditionnel","Simplified":"Simplifié","Nothing could be read.":"Rien n'a pu être lu.","Reading the text …":"Lecture du texte …",
  "meaning unverified":"sens non vérifié"," (translation pending)":" (traduction en attente)"," (reading uncertain: {0})":" (lecture incertaine : {0})",
  "Also on another photo":"Aussi sur une autre photo","Also on {0} other photos":"Aussi sur {0} autres photos","Show this photo":"Afficher cette photo","Open this card":"Ouvrir cette carte",
  "Loading the dictionary …":"Chargement du dictionnaire …","not in the dictionary":"absent du dictionnaire","Dictionary not available.":"Dictionnaire indisponible.","Pronounce":"Prononcer",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"Pas de voix chinoise sur ce téléphone – ajoutez-en une dans Réglages, Synthèse vocale.",
  "⚑ Review":"⚑ À vérifier","New":"Nouvelle","Review":"Révision","⚑ Flagged for review":"⚑ Signalée à vérifier",
  "failed {0} times in a row — check text, meaning and photo":"ratée {0} fois de suite – vérifiez le texte, le sens et la photo",
  "AI: this text looks misread":"IA : ce texte semble mal lu","Dismiss":"Ignorer","AI suggestion":"Suggestion de l'IA",": looks right":" : semble correct","Accept":"Accepter","Mark verified":"Marquer comme vérifié","Accept all":"Tout accepter",
  "All cards":"Toutes les cartes","Untagged":"Sans étiquette","Untagged ({0})":"Sans étiquette ({0})",
  "Nothing read":"Rien de lu","Reading …":"Lecture …","AI":"IA","No cards match.":"Aucune carte ne correspond.",
  "No cards yet — take a photo under Camera, or tap + New.":"Pas encore de cartes – prenez une photo sous Photo, ou touchez + Nouvelle.",
  "Search":"Rechercher","+ New":"+ Nouvelle","⚑ Flagged ({0})":"⚑ Signalées ({0})","AI ({0})":"IA ({0})","Unverified ({0})":"Non vérifiées ({0})","{0} of {1}":"{0} sur {1}",
  "due":"à faire","in {0} d":"dans {0} j",
  "Interval {0} d, ease {1}, {2}, next {3}.":"Intervalle {0} j, facilité {1}, {2}, prochaine {3}.","Not studied yet.":"Pas encore étudiée.",
  "Nothing read yet":"Rien de lu encore","unverified":"non vérifié","translation pending":"traduction en attente","reading uncertain":"lecture incertaine",
  "The new frame is being read — the text follows when it is done.":"Le nouveau cadre est en cours de lecture – le texte suivra.",
  "The text, pinyin and meaning follow when the reading is done.":"Le texte, le pinyin et le sens suivront une fois la lecture terminée.",
  "Tap the character to show the answer":"Touchez le caractère pour afficher la réponse","Tap the character to hide the answer":"Touchez le caractère pour masquer la réponse",
  "Test this card":"Tester cette carte","Edit":"Modifier","Delete card":"Supprimer la carte","Delete “{0}”?":"Supprimer « {0} » ?","Delete this card?":"Supprimer cette carte ?",
  "The card and its learning progress will be removed.":"La carte et sa progression seront supprimées.","Delete":"Supprimer","Cancel":"Annuler",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"Vous êtes dans WeChat. Ouvrez cette page dans votre navigateur pour installer l'application et garder vos cartes."
},
es:{
  "time":"{0} vez","times":"{0} veces","AI check":"{0} comprobación de la IA","AI checks":"{0} comprobaciones de la IA",
  "Due":"Pendientes","Done":"Hechas","Deck":"Tarjetas","Learn":"Aprender","Cards":"Tarjetas","Camera":"Cámara","More":"Más",
  "Language":"Idioma","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"Los textos de la app. Las tarjetas conservan el chino, el pinyin y el significado.",
  "Loading …":"Cargando …","No cards yet.":"Aún no hay tarjetas.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"Fotografía un letrero, una carta o un envase en <b>Cámara</b>, o añade una palabra a mano en <b>Tarjetas → + Nueva</b>.",
  "Take a photo":"Hacer una foto","All clear.":"Todo hecho.","Pulled-forward round finished.":"Ronda adelantada terminada.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"Nada pendiente hoy. Vuelve mañana, o adelanta las siguientes tarjetas.",
  "Pull the next cards forward":"Adelantar las siguientes tarjetas","Again":"Otra vez","Hard":"Difícil","Good":"Bien","Easy":"Fácil",
  "⚑ Clear flag":"⚑ Quitar la marca","⚑ Flag for review":"⚑ Marcar para revisar","✎ Edit":"✎ Editar",
  "Tap the character to reveal":"Toca el carácter para ver la respuesta",", or the photo for the whole picture":", o la foto para ver la imagen entera",
  "← Cards":"← Tarjetas","Testing from the list":"Prueba desde la lista","<10 min":"<10 min","<1 d":"<1 d","1 d":"1 d","{0} d":"{0} d",
  "{0} learned, {1} reviewed this week, streak {2}":"{0} aprendidas, {1} repasadas esta semana, racha de {2}",
  "card":"{0} tarjeta","cards":"{0} tarjetas","day":"{0} día","days":"{0} días","review":"{0} repaso","reviews":"{0} repasos","photo":"{0} foto","photos":"{0} fotos",
  "AI suggestion waiting":"{0} sugerencia de la IA en espera","AI suggestions waiting":"{0} sugerencias de la IA en espera",
  "Traditional":"Tradicional","Simplified":"Simplificado","Nothing could be read.":"No se pudo leer nada.","Reading the text …":"Leyendo el texto …",
  "meaning unverified":"significado sin verificar"," (translation pending)":" (traducción pendiente)"," (reading uncertain: {0})":" (lectura dudosa: {0})",
  "Also on another photo":"También en otra foto","Also on {0} other photos":"También en otras {0} fotos","Show this photo":"Mostrar esta foto","Open this card":"Abrir esta tarjeta",
  "Loading the dictionary …":"Cargando el diccionario …","not in the dictionary":"no está en el diccionario","Dictionary not available.":"Diccionario no disponible.","Pronounce":"Pronunciar",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"Este teléfono no tiene voz china: añade una en Ajustes, Salida de texto a voz.",
  "⚑ Review":"⚑ Revisar","New":"Nueva","Review":"Repaso","⚑ Flagged for review":"⚑ Marcada para revisar",
  "failed {0} times in a row — check text, meaning and photo":"fallada {0} veces seguidas: revisa el texto, el significado y la foto",
  "AI: this text looks misread":"IA: este texto parece mal leído","Dismiss":"Descartar","AI suggestion":"Sugerencia de la IA",": looks right":": parece correcto","Accept":"Aceptar","Mark verified":"Marcar como verificada","Accept all":"Aceptar todas",
  "All cards":"Todas las tarjetas","Untagged":"Sin etiqueta","Untagged ({0})":"Sin etiqueta ({0})",
  "Nothing read":"Nada leído","Reading …":"Leyendo …","AI":"IA","No cards match.":"Ninguna tarjeta coincide.",
  "No cards yet — take a photo under Camera, or tap + New.":"Aún no hay tarjetas: haz una foto en Cámara o toca + Nueva.",
  "Search":"Buscar","+ New":"+ Nueva","⚑ Flagged ({0})":"⚑ Marcadas ({0})","AI ({0})":"IA ({0})","Unverified ({0})":"Sin verificar ({0})","{0} of {1}":"{0} de {1}",
  "due":"pendiente","in {0} d":"en {0} d",
  "Interval {0} d, ease {1}, {2}, next {3}.":"Intervalo {0} d, facilidad {1}, {2}, próximo {3}.","Not studied yet.":"Aún no estudiada.",
  "Nothing read yet":"Aún nada leído","unverified":"sin verificar","translation pending":"traducción pendiente","reading uncertain":"lectura dudosa",
  "The new frame is being read — the text follows when it is done.":"Se está leyendo el nuevo recorte: el texto llegará cuando termine.",
  "The text, pinyin and meaning follow when the reading is done.":"El texto, el pinyin y el significado llegarán cuando termine la lectura.",
  "Tap the character to show the answer":"Toca el carácter para mostrar la respuesta","Tap the character to hide the answer":"Toca el carácter para ocultar la respuesta",
  "Test this card":"Probar esta tarjeta","Edit":"Editar","Delete card":"Eliminar tarjeta","Delete “{0}”?":"¿Eliminar «{0}»?","Delete this card?":"¿Eliminar esta tarjeta?",
  "The card and its learning progress will be removed.":"Se eliminarán la tarjeta y su progreso.","Delete":"Eliminar","Cancel":"Cancelar",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"Estás dentro de WeChat. Abre esta página en tu navegador para instalar la app y conservar tus tarjetas."
},
ja:{
  "time":"{0}回","times":"{0}回","AI check":"AI確認{0}回","AI checks":"AI確認{0}回",
  "Due":"今日","Done":"済み","Deck":"カード","Learn":"学習","Cards":"カード","Camera":"カメラ","More":"その他",
  "Language":"言語","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"アプリの表示言語です。カードの中国語・ピンイン・意味は変わりません。",
  "Loading …":"読み込み中 …","No cards yet.":"カードはまだありません。",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"<b>カメラ</b>で看板・メニュー・パッケージを撮影するか、<b>カード → + 新規</b>で単語を手入力してください。",
  "Take a photo":"写真を撮る","All clear.":"今日の分は終わりました。","Pulled-forward round finished.":"前倒しの復習が終わりました。",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"今日の復習はありません。明日また来るか、次のカードを前倒しできます。",
  "Pull the next cards forward":"次のカードを前倒しする","Again":"もう一度","Hard":"難しい","Good":"普通","Easy":"簡単",
  "⚑ Clear flag":"⚑ 印を外す","⚑ Flag for review":"⚑ 要確認の印","✎ Edit":"✎ 編集",
  "Tap the character to reveal":"文字をタップすると答えが表示されます",", or the photo for the whole picture":"。写真をタップすると全体が見られます",
  "← Cards":"← カード","Testing from the list":"一覧からテスト中","<10 min":"<10分","<1 d":"<1日","1 d":"1日","{0} d":"{0}日",
  "{0} learned, {1} reviewed this week, streak {2}":"習得 {0}、今週の復習 {1}、連続 {2}",
  "card":"カード{0}枚","cards":"カード{0}枚","day":"{0}日","days":"{0}日","review":"{0}回","reviews":"{0}回","photo":"写真{0}枚","photos":"写真{0}枚",
  "AI suggestion waiting":"AIの提案 {0} 件","AI suggestions waiting":"AIの提案 {0} 件",
  "Traditional":"繁体字","Simplified":"簡体字","Nothing could be read.":"何も読み取れませんでした。","Reading the text …":"文字を読み取り中 …",
  "meaning unverified":"意味は未確認"," (translation pending)":"（翻訳待ち）"," (reading uncertain: {0})":"（読み取りが不確か: {0}）",
  "Also on another photo":"別の写真にもあります","Also on {0} other photos":"他の {0} 枚の写真にもあります","Show this photo":"この写真を表示","Open this card":"このカードを開く",
  "Loading the dictionary …":"辞書を読み込み中 …","not in the dictionary":"辞書にありません","Dictionary not available.":"辞書を使えません。","Pronounce":"発音",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"この端末に中国語の音声がありません。設定の「テキスト読み上げ」で追加してください。",
  "⚑ Review":"⚑ 要確認","New":"新規","Review":"復習","⚑ Flagged for review":"⚑ 要確認の印付き",
  "failed {0} times in a row — check text, meaning and photo":"{0} 回続けて不正解 — 文字・意味・写真を確認してください",
  "AI: this text looks misread":"AI: この文字は読み間違いのようです","Dismiss":"閉じる","AI suggestion":"AIの提案",": looks right":": 問題なさそうです","Accept":"採用","Mark verified":"確認済みにする","Accept all":"すべて採用",
  "All cards":"すべてのカード","Untagged":"タグなし","Untagged ({0})":"タグなし ({0})",
  "Nothing read":"読み取れず","Reading …":"読み取り中 …","AI":"AI","No cards match.":"該当するカードがありません。",
  "No cards yet — take a photo under Camera, or tap + New.":"カードはまだありません。カメラで撮影するか、+ 新規をタップしてください。",
  "Search":"検索","+ New":"+ 新規","⚑ Flagged ({0})":"⚑ 要確認 ({0})","AI ({0})":"AI ({0})","Unverified ({0})":"未確認 ({0})","{0} of {1}":"{0} / {1}",
  "due":"今日","in {0} d":"{0}日後",
  "Interval {0} d, ease {1}, {2}, next {3}.":"間隔 {0} 日、易しさ {1}、{2}、次回 {3}。","Not studied yet.":"まだ学習していません。",
  "Nothing read yet":"まだ読み取れていません","unverified":"未確認","translation pending":"翻訳待ち","reading uncertain":"読み取りが不確か",
  "The new frame is being read — the text follows when it is done.":"新しい範囲を読み取り中です。終わると文字が入ります。",
  "The text, pinyin and meaning follow when the reading is done.":"読み取りが終わると文字・ピンイン・意味が入ります。",
  "Tap the character to show the answer":"文字をタップすると答えが表示されます","Tap the character to hide the answer":"文字をタップすると答えが隠れます",
  "Test this card":"このカードをテスト","Edit":"編集","Delete card":"カードを削除","Delete “{0}”?":"「{0}」を削除しますか？","Delete this card?":"このカードを削除しますか？",
  "The card and its learning progress will be removed.":"カードと学習記録が削除されます。","Delete":"削除","Cancel":"キャンセル",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"WeChat 内で開いています。アプリをインストールしてカードを残すには、ブラウザでこのページを開いてください。"
},
ko:{
  "time":"{0}번","times":"{0}번","AI check":"AI 확인 {0}회","AI checks":"AI 확인 {0}회",
  "Due":"오늘","Done":"완료","Deck":"카드","Learn":"학습","Cards":"카드","Camera":"카메라","More":"더보기",
  "Language":"언어","The app's own texts. Cards keep their Chinese, pinyin and meaning.":"앱의 표시 언어입니다. 카드의 중국어, 병음, 뜻은 그대로입니다.",
  "Loading …":"불러오는 중 …","No cards yet.":"아직 카드가 없습니다.",
  "Photograph a sign, a menu or a package under <b>Camera</b> — or add a word by hand under <b>Cards → + New</b>.":"<b>카메라</b>에서 간판, 메뉴, 포장을 찍거나 <b>카드 → + 새로 만들기</b>에서 단어를 직접 입력하세요.",
  "Take a photo":"사진 찍기","All clear.":"오늘 분량을 마쳤습니다.","Pulled-forward round finished.":"앞당긴 복습을 마쳤습니다.",
  "Nothing due today. Come back tomorrow — or pull the next cards forward.":"오늘 복습할 카드가 없습니다. 내일 다시 오거나 다음 카드를 앞당길 수 있습니다.",
  "Pull the next cards forward":"다음 카드 앞당기기","Again":"다시","Hard":"어려움","Good":"보통","Easy":"쉬움",
  "⚑ Clear flag":"⚑ 표시 지우기","⚑ Flag for review":"⚑ 검토 표시","✎ Edit":"✎ 편집",
  "Tap the character to reveal":"글자를 누르면 답이 보입니다",", or the photo for the whole picture":". 사진을 누르면 전체 사진이 보입니다",
  "← Cards":"← 카드","Testing from the list":"목록에서 테스트 중","<10 min":"<10분","<1 d":"<1일","1 d":"1일","{0} d":"{0}일",
  "{0} learned, {1} reviewed this week, streak {2}":"학습 {0}, 이번 주 복습 {1}, 연속 {2}",
  "card":"카드 {0}장","cards":"카드 {0}장","day":"{0}일","days":"{0}일","review":"{0}회","reviews":"{0}회","photo":"사진 {0}장","photos":"사진 {0}장",
  "AI suggestion waiting":"AI 제안 {0}개 대기 중","AI suggestions waiting":"AI 제안 {0}개 대기 중",
  "Traditional":"번체자","Simplified":"간체자","Nothing could be read.":"아무것도 읽지 못했습니다.","Reading the text …":"글자를 읽는 중 …",
  "meaning unverified":"뜻 미확인"," (translation pending)":" (번역 대기)"," (reading uncertain: {0})":" (읽기 불확실: {0})",
  "Also on another photo":"다른 사진에도 있음","Also on {0} other photos":"다른 사진 {0}장에도 있음","Show this photo":"이 사진 보기","Open this card":"이 카드 열기",
  "Loading the dictionary …":"사전을 불러오는 중 …","not in the dictionary":"사전에 없음","Dictionary not available.":"사전을 사용할 수 없습니다.","Pronounce":"발음",
  "No Chinese voice on this phone — add one under Settings, Text-to-speech output.":"이 기기에 중국어 음성이 없습니다. 설정의 '텍스트 음성 변환'에서 추가하세요.",
  "⚑ Review":"⚑ 검토","New":"새 카드","Review":"복습","⚑ Flagged for review":"⚑ 검토 표시됨",
  "failed {0} times in a row — check text, meaning and photo":"{0}회 연속 틀림 — 글자, 뜻, 사진을 확인하세요",
  "AI: this text looks misread":"AI: 이 글자는 잘못 읽힌 것 같습니다","Dismiss":"닫기","AI suggestion":"AI 제안",": looks right":": 맞는 것 같습니다","Accept":"적용","Mark verified":"확인됨으로 표시","Accept all":"모두 적용",
  "All cards":"모든 카드","Untagged":"태그 없음","Untagged ({0})":"태그 없음 ({0})",
  "Nothing read":"읽지 못함","Reading …":"읽는 중 …","AI":"AI","No cards match.":"일치하는 카드가 없습니다.",
  "No cards yet — take a photo under Camera, or tap + New.":"아직 카드가 없습니다. 카메라에서 사진을 찍거나 + 새로 만들기를 누르세요.",
  "Search":"검색","+ New":"+ 새로 만들기","⚑ Flagged ({0})":"⚑ 표시됨 ({0})","AI ({0})":"AI ({0})","Unverified ({0})":"미확인 ({0})","{0} of {1}":"{0} / {1}",
  "due":"오늘","in {0} d":"{0}일 후",
  "Interval {0} d, ease {1}, {2}, next {3}.":"간격 {0}일, 난이도 계수 {1}, {2}, 다음 {3}.","Not studied yet.":"아직 학습하지 않았습니다.",
  "Nothing read yet":"아직 읽지 못함","unverified":"미확인","translation pending":"번역 대기","reading uncertain":"읽기 불확실",
  "The new frame is being read — the text follows when it is done.":"새 영역을 읽는 중입니다. 끝나면 글자가 채워집니다.",
  "The text, pinyin and meaning follow when the reading is done.":"읽기가 끝나면 글자, 병음, 뜻이 채워집니다.",
  "Tap the character to show the answer":"글자를 누르면 답이 보입니다","Tap the character to hide the answer":"글자를 누르면 답이 숨겨집니다",
  "Test this card":"이 카드 테스트","Edit":"편집","Delete card":"카드 삭제","Delete “{0}”?":"“{0}”을(를) 삭제할까요?","Delete this card?":"이 카드를 삭제할까요?",
  "The card and its learning progress will be removed.":"카드와 학습 기록이 삭제됩니다.","Delete":"삭제","Cancel":"취소",
  "You are inside WeChat. Open this page in your browser to install the app and keep your cards.":"WeChat 안에서 열려 있습니다. 앱을 설치하고 카드를 보관하려면 브라우저에서 이 페이지를 여세요."
}
};
